### ISSUE TITLE
kop

### ISSUE THREAD

**Issue by Linuxstyle** [apache/pulsar-helm-chart#132]
How to deploy kop in k8s?

**Comment by liangyuanpeng** [comment]
In my case, i need mop.

**Comment by nlandeker** [comment]
Hi, is this something that will be done or should we search for other solutions?

Thanks

**Comment by eolivelli** [comment]
Hello, I am working on an Open Source Helm Chart that supports KOP, but it is not based on the official Apache Pulsar docker images and Helm Charts. Basically because the Official Apache Pulsar docker images do not contain third party components like the KOP protocol handler.
If you are interested you can reach out to me via Slack

By the way it is pretty simple to achieve this goal:
- create a Dockerfile that starts from the official Pulsar docker images
- add the KOP nar file in /pulsar/protocols
- build and push your new image somewhere on dockerhub or in your private docker registry
- configure the broker configuration in order to bootstrap KOP
- set the docker image for the broker service to use your custom docker image

**Comment by nlandeker** [comment]
Hello, @eolivelli I am definitely interested but unsure on how to reach you on Slack :)

**Comment by eolivelli** [comment]
> Hello, @eolivelli I am definitely interested but unsure on how to reach you on Slack :)

Subscribe to Slack here
https://pulsar.apache.org/en/contact/

My name is "Enrico Olivelli" :-)

**Comment by codelipenghui** [comment]
Here is a chart which contains kop and mop https://github.com/streamnative/charts/blob/master/charts/pulsar/values.yaml#L94

**Comment by ChenJhua** [comment]
i need kop too
