### ISSUE TITLE
Can I use K8S HPA for proxy, broker and bookie ? Thanks.

### ISSUE THREAD

**Issue by Kiddinglife** [apache/pulsar-helm-chart#139]

**Comment by ckdarby** [comment]
Yes, here is the documentation on K8s HPA, [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/).

You'll need to pick the correct metrics for each one of those components and make sure to limit your downscaling on the bookies because you won't want to downscale faster than replication can happen to keep the cluster healthy.

For example, let's say you have 10 replica bookies and downscale down to 7 without pause or not enough for autorecovery to fix replication. In this scenario, you've potentially lost data for any data that was written across only those bookies (bookie-9, bookie-8, bookies-7) that have been scaled down now.

**Comment by Kiddinglife** [comment]
Thx. I am now using stream native operator as auto scaler, which looks more promising and stable.
