### ISSUE TITLE
chage the pulsar-manager port

### ISSUE THREAD

**Issue by chlyzzo** [apache/pulsar-helm-chart#156]
**Is your feature request related to a problem? Please describe.**
in k8s, helm install pulsar, and gei services, like :
pulsar-spatio-pulsar-manager   NodePort       10.233.46.47    <none>        9527:31335/TCP                100m
and the port 31335 can random change, when uninstall pulsar-spatio then install again,

**Describe the solution you'd like**
so ,how can set port in values.yaml, can get a define port to pulsar-spatio-pulsar-manager.
   for example, in values.yaml i set a parameter（now i do not know which parameter）,then install puslar, can get 
pulsar-spatio-pulsar-manager   NodePort       10.233.46.47    <none>        9527:8100/TCP                100m

**Describe alternatives you've considered**

**Additional context**

**Comment by michaeljmarshall** [comment]
I provided an answer to this issue here: https://github.com/apache/pulsar/issues/11909#issuecomment-917219256. It is not possible to configure the node port to 8100, as node ports must be in the range from 30000 to 32767.

@chlyzzo - are you still looking to configure the node port? If so, you could do this by modifying the service templates. Would you like to contribute this feature?

**Comment by lhotari** [comment]
Closing issue since there's no feedback from reporter. pulsar-manager integration was improved in #457
