### ISSUE TITLE
topic lose: helm install --values examples/values-minikube.yaml --set initialize=true --namespace pulsar-st pulsar-minikube ./charts/pulsar

### ISSUE THREAD

**Issue by chlyzzo** [apache/pulsar-helm-chart#160]
**Is your feature request related to a problem? Please describe.**
first, i clone apache/pulsar-helm-chart, on k8s machine, i use the command:
-------
helm install --values examples/values-minikube.yaml --set initialize=true --namespace pulsar-st pulsar-minikube ./charts/pulsar
---------
install a pulsar;
then i get a pulsar, so i use the command into pulsar:
kubectl exec -it -n pulsar-st pulsar-minikube-toolset-0 -- /bin/bash

and then produce a message:
./bin/pulsar-client produce my-topic --messages "dsfs334"

and list the topics:
./bin/pulsar-admin topics list public/default

i can see the :
"persistent://public/default/my-topic"

**Describe the solution you'd like**
but after a few seconds, the topics lose, and do not consume the message from topic,
use the command:./bin/pulsar-admin topics list public/default
and get nothing.

**Describe alternatives you've considered**
so, helm install pussar,the topics lose, 

**Additional context**

**Comment by lhotari** [comment]
I think it's intentional that `examples/values-minikube.yaml` doesn't have persistence enabled. `--set volumes.persistence=true` should resolve this issue. You also need support for PVCs. It might require installing Rancher Local Path Provisioner: https://github.com/rancher/local-path-provisioner#installation to support that in test environments. 
Nowadays a good alternative for minikube and Docker desktop is Rancher Desktop, which is free and open source. It includes a k8s environment based on k3s. https://rancherdesktop.io/
