### ISSUE TITLE
Release tag pulsar-2.9.3 is not matching the images version in values.yaml

### ISSUE THREAD

**Issue by youg9203** [apache/pulsar-helm-chart#265]
Hello,

Is that intentional or a mistake, I believe it supposes to match the pulsar version, if not then I would suggest adding the build number in the version, the original version must be synced with the apache-pulsar version.

Please correct me if I'm wrong, or did I miss something here?

Thanks

**Comment by michaeljmarshall** [comment]
The chart's `version` does not need to align with the version of Apache Pulsar that ships with it by default. That is the purpose of the `appVersion` field in the `Chart.yaml` see here https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/Chart.yaml.

The primary reason we have diverged is that it is helpful to decouple helm chart and Apache Pulsar releases so that helm chart features can ship faster. That being said, we could probably do a better job of documenting the version of pulsar that the chart is currently using. Maybe we could do this with some kind of button at the top of the README?
