### ISSUE TITLE
Plan for the next release of the chart

### ISSUE THREAD

**Issue by Giaco9** [apache/pulsar-helm-chart#408]
Hi everyone. We are using this chart to run Pulsar in our production environment, and we are interested in understanding the plan for a new release. Especially, we are interested in [this pull request](https://github.com/apache/pulsar-helm-chart/pull/354) which would allow us to keep using the chart and upgrade our EKS cluster to version 1.26.

These are the commits added since the last release: https://github.com/apache/pulsar-helm-chart/compare/pulsar-3.0.0...master

Thank you

Giacomo

**Comment by emre-aydin** [comment]
Hi. I think a new version of the Helm chart should be released soon. The [current documentation for Helm deploy](https://pulsar.apache.org/docs/3.1.x/helm-deploy/) in the official docs don't work as is when you enable the proxy because of a port binding issue. When you follow the official docs, you end up helm installating the latest released version but the commit that fixes this issue is not released yet.

**Comment by Giaco9** [comment]
Hi @emre-aydin, thank you for the info :) is the commit to fix the port binding issue merged in the main branch?

**Comment by emre-aydin** [comment]
Hi @Giaco9 , yep. [This](https://github.com/apache/pulsar-helm-chart/commit/90a26b2dc885e0a76e33133cf297f8ac6a402c23) is the one I'm talking about.

**Comment by Giaco9** [comment]
Ok, this is a good news, but the commit has been merged 4 months ago, so my answer about planning for the next release still remains. Is there anyone should we ask for creating a new release candidate?

**Comment by tripolif98** [comment]
Any news on the next release of the helm chart??

**Comment by hpvd** [comment]
see: https://github.com/apache/pulsar-helm-chart/issues/364#event-11207736285

**Comment by lhotari** [comment]
Closing this issue since the release is in progress.
