### ISSUE TITLE
Optional Roles and Service Accounts

### ISSUE THREAD

**Issue by Mortom123** [apache/pulsar-helm-chart#424]
**Is your feature request related to a problem? Please describe.**
Some cluster provider are strict with their roles / service accounts. A way to completely turn of Role creation, Role binding and Service Account creation (use the default service account provided in a namespace) would enable easier deployment in such scenarios.

**Describe the solution you'd like**
Add in values.yaml: `rbac.use_default_account` which toggles the aforementioned k8s kinds to not be deployed and instead use the default account provided (this could also be another option to set)

**Describe alternatives you've considered**
None

**Additional context**
Would be willing to submit a PR. :)

**Comment by lhotari** [comment]
Usually the problem is the usage of ClusterRoles and ClusterRoleBindings. Those are no longer the default after #418 was merged. That change will be included in the chart's upcoming 3.2.0 release which is currently in voting stage. 

What you are proposing most likely makes sense. I'm looking forward to your PR.

**Comment by Mortom123** [comment]
After some more trial and error, it turns out that really just the (Cluster)Role and (Cluster)RoleBindings were the problem. ServiceAccount creation seems to be perfectly fine. Will close this Feature Request as it was made out of false assumptions.
