### ISSUE TITLE
[CI] ci::test_pulsar_manager environment check is flaky

### ISSUE THREAD

**Issue by lhotari** [apache/pulsar-helm-chart#460]
**Describe the bug**

ci::test_pulsar_manager is environment check is flaky

Example in https://github.com/apache/pulsar-helm-chart/actions/runs/7912837143/job/21599359914#step:6:4929
```
Performing login
{"login":"success"}Checking environment
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    21    0    21    0     0    362      0 --:--:-- --:--:-- --:--:--   362
Error: Did not find expected environment
Error: Process completed with exit code 1.
````

After re-running, the check passed.

**Expected behavior**

The check shouldn't be flaky.

**Comment by lhotari** [comment]
@Mortom123 any ideas?

**Comment by Mortom123** [comment]
Not really. Also the account seems to be created, while the environment is not (yet?). But both are done in the same job.

**Comment by Mortom123** [comment]
I'm currently investigating - https://github.com/Mortom123/pulsar-helm-chart/pull/3. And it seems the pulsar-manager test is only a symptom, and not the complete picture (at least from my understanding). 

To see what I mean have a look here:
https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7928137620 - kube-prometheus test fails
https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7930141638 - TLS fails
https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7929918393/job/21651157455 - Pulsar Manager fails

They all have one thing in common - they try to access the broker. Furthermore, looking through the errors it becomes evident that all of these test fail because they cannot connect to the broker. 
See [here ](https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7929918393/job/21651157455#step:6:5503) in the case of the manager problem. 

Maybe something with this [code ](https://github.com/apache/pulsar-helm-chart/blob/master/charts/pulsar/templates/proxy-statefulset.yaml#L129) is not working as expected? Or the broker encounters an error and starts to restart?

**Comment by Mortom123** [comment]
Any advice / idea @lhotari ?

**Comment by lhotari** [comment]
@Mortom123 do you have a chance to make a contribution to address this? I'd like to get this resolved before starting the release for Apache Pulsar Helm chart 3.3.0 since this issue seems to also impact actual usage of the Pulsar Manager feature.  The init job doesn't do it's job when it hits the `{"error":"This environment is error. Please check it"}` issue.

**Comment by Mortom123** [comment]
@lhotari  I do not think that the problem lies within the manager, but rather the underlying k8 deployment. The Pulsar Manager throws this issue because it cannot resolve the name `pulsar-ci-broker`, other tests (TLS/kube-prometheus) fail for the same reason.

**Comment by lhotari** [comment]
> @lhotari I do not think that the problem lies within the manager, but rather the underlying k8 deployment. The Pulsar Manager throws this issue because it cannot resolve the name `pulsar-ci-broker`, other tests (TLS/kube-prometheus) fail for the same reason.
> 
> The logs from within the pulsar manager container are starting from here: https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7929918393/job/21651157455#step:6:5240 The error is at: https://github.com/Mortom123/pulsar-helm-chart/actions/runs/7929918393/job/21651157455#step:6:5503

In this case, everything else passed: https://github.com/apache/pulsar-helm-chart/actions/runs/7989357049/job/21816701126#step:6:4990

The pulsar-ci-broker name cannot be resolved before the readiness probe passes. The init job should retry if it receives `{"error":"This environment is error. Please check it"}`. That's one way to handle this. [The quirk in pulsar-manager is that the REST call returns 200 even when there's a failure.](https://github.com/apache/pulsar-manager/blob/ee83cd22c99c44091b3b37054cdcffec4284dadf/src/main/java/org/apache/pulsar/manager/controller/EnvironmentsController.java#L152-L154)

**Comment by lhotari** [comment]
Just wondering if limiting the memory for that pulsar-manager Java process would be useful? Something like this in
`.ci/values-common.yaml`:
```
pulsar_manager:
  configData:
    PULSAR_MANAGER_OPTS: "-Xmx200M -Dlog4j2.formatMsgNoLookups=true"
```

**Comment by lhotari** [comment]
I guess we could replace `-Xmx200M` with `-XX:MaxRAMPercentage=70.0` so that the memory size adjusts according to the requests / limits. Azul's doc about it: https://docs.azul.com/prime/Heap-Size
