### ISSUE TITLE
Error Reading Functions Worker ConfigMap

### ISSUE THREAD

**Issue by toneill818** [apache/pulsar-helm-chart#56]
**Describe the bug**
When enabling functions, the broker throws the following error:

> Error while trying to fetch configmap pulsar-functions-worker-config at namespace

**To Reproduce**
1. Set Components.functions to True (true by default)
2. View broker logs

**Expected behavior**
I think the role needs to be bound to the broker service account. It currently creates another service account named `pulsar-functions-worker`. Not sure if that SA is used by the functions, but the `pulsar-broker-acct` does not have access to the function worker config map.

What is the `pulsar-functions-worker` used for? Is it used by the functions? If so we can add read access to the `pulsar-broker-acct` role that is bound so it can read the ConfigMap.

**Comment by Syphixs** [comment]
![image](https://user-images.githubusercontent.com/33832024/103174599-c9d3df80-4863-11eb-9b99-ce71aaf2ce5d.png)

Sadly this error still persists even in 2.7
Still can't figure out the error, even created the clusterrole from stretch again like described in [Function Docs](https://pulsar.apache.org/docs/en/functions-runtime/)

**Comment by lhotari** [comment]
the functions-worker-config map is a feature which doesn't work at all. it is explained at https://github.com/apache/pulsar-helm-chart/pull/392#discussion_r1498309625 .
I have another comment where the Functions Worker configuration is explained: 
https://github.com/apache/pulsar-helm-chart/issues/382#issuecomment-1957951168

I'm going to fix this issue by removing the pulsar-functionw-worker-config map since it's just causing confusion and doesn't work.
